# Generated by Django 5.2.16 on 2026-08-05 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_regenerate_event_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reminderlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventaction',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventaction',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='planning_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.planningcall'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='reminder_type',
            field=models.CharField(choices=[('event_upcoming', 'Event upcoming'), ('action_deadline', 'Action deadline'), ('call_reminder', 'Planning call reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='window_label',
            field=models.CharField(help_text='e.g. "7d", "1d", dedupes per reminder window.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reminderlog',
            unique_together={('user', 'event', 'event_action', 'planning_call', 'reminder_type', 'window_label')},
        ),
        migrations.CreateModel(
            name='CallRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_attend', models.BooleanField(default=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.planningcall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('call', 'user')},
            },
        ),
    ]
