# Generated by Django 5.2.16 on 2026-08-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_reminderlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningcall',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text="When the call is expected to wrap up -- shown to attendees as the call's length.", null=True),
        ),
    ]
