# Generated by Django 5.2.16 on 2026-08-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_action_completions(apps, schema_editor):
    """Completion used to be a single shared flag on EventAction -- carry
    forward whoever last checked one off as their own per-user completion
    row before the shared fields are dropped below."""
    EventAction = apps.get_model('events', 'EventAction')
    ActionCompletion = apps.get_model('events', 'ActionCompletion')
    completed = EventAction.objects.filter(is_completed=True, completed_by__isnull=False)
    for action in completed:
        ActionCompletion.objects.get_or_create(action=action, user_id=action.completed_by_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_planningcall_ends_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='events.eventaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('action', 'user')},
            },
        ),
        migrations.RunPython(backfill_action_completions, noop),
        migrations.RemoveField(
            model_name='eventaction',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='eventaction',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='eventaction',
            name='is_completed',
        ),
    ]
