# Generated by Django 5.2.16 on 2026-08-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_username_matches_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account "sub" identifier, set once a user signs in with Google.', max_length=64, null=True, unique=True),
        ),
    ]
